language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '2.2.15'
rvm:
  - "2.2.0"
  - "2.3.0"
  - "2.4.0"
  - "2.5.0"
  - "2.6.0"
  - "2.7.0"
  - "3.0.0"
before_install:
 - sudo apt-get install -qq libjpeg-progs optipng
script: bundle exec rspec -b spec